#!/usr/bin/env perl

use strict;
use warnings;

use lib $ENV{'MUNIN_LIBDIR'};
use Munin::Plugin;

use Redis;

my $redis = Redis->new(server => "$ENV{'server'}:$ENV{'port'}" ) or die;
$redis->select($ENV{'dbindex'}) or die;

if ( defined($ARGV[0]) and $ARGV[0] eq "autoconf" ) {
	print "yes\n";
	exit 0;
}

if ( defined($ARGV[0]) and $ARGV[0] eq "config" ) {
	map {
		my $cname = $redis->hget($_, 'name');

		print "multigraph $_\n";
		print "graph_title $cname\n";
		print "graph_category $Munin::Plugin::me\n\n";
	} $redis->smembers($ENV{'key'});

	exit 0;
}

# dump values
map {
	my $cname = $redis->hget($_, 'name');
	my $cvalue = $redis->hget($_, 'value');

	print "multigraph $Munin::Plugin::me.$_\n";
	print "counter.value " . $cvalue. "\n\n";
} $redis->smembers($ENV{'key'});
